### ISSUE TITLE
Does this allow for quality (e.g. 1080p) setting?

### ISSUE THREAD

**Issue by actuallymentor** [Deathspike/crunchyroll.js#14]
Hello,

Does this tool allow for specification of the quality you want do download? The webinterface allows for 480/720/1080p. I'd love to download some episodes for mobile offline watching, but am an HD addict.

Thanks,

**Comment by Fendoroid** [comment]
Yes, you can change your crunchyroll account settings, using browser, under settings/video preferences.

**Comment by actuallymentor** [comment]
Perfect, thanks :)
