### ISSUE TITLE
Don't working in Mac Captain Last Version

### ISSUE THREAD

**Issue by RafaelPlantard** [Deathspike/crunchyroll.js#21]
Can you show me a sample of entering an auth version..
I'm trying download the Kuroko's Basketball, I have a premium account.

**Comment by Jfigs101** [comment]
What do you mean by 'auth version'?

**Comment by RafaelPlantard** [comment]
With user and password args...

**Comment by Jfigs101** [comment]
An example would be 

crunchyroll -u username -p password -o C:\folderpath URL

Replace username with your username or email and exchange password for your password. If your show you are trying to download is available in your country that should work.

**Comment by RafaelPlantard** [comment]
I did it: 

`crunchyroll -u user@email.com -p pass -o ~/Downloads http://www.crunchyroll.com/kurokos-basketball`

But does not works...
That command did not return errors or results.

**Comment by Jfigs101** [comment]
I copy and pasted your command above and substituted my credentials and it worked.

**Comment by RafaelPlantard** [comment]
Really?

**Comment by Godzil** [comment]
I your password have non alpha character you may need to surround it with quotes

**Comment by RafaelPlantard** [comment]
I will try 💃
