### ISSUE TITLE
Odd error

### ISSUE THREAD

**Issue by RedstoneGeek223** [Deathspike/crunchyroll.js#28]
On download command execute I get this error:

<blockquote>************@****************OptiPlex-780:~$ sudo crunchyroll -o /media/plasma-blast/Anime/Digimon/Tamers -u ************ -p *********** -c -m "http://www.crunchyroll.com/digimon-tamers/"
[sudo] password for plasma-blast: 
Fetching Digimon Tamers 01x01 [CrunchyRoll]
Error: Command failed: /bin/sh -c rtmpdump -r "" -y "http://serve.cxcdn.net/s/v/rvzai77rh8ey403/m/0264121600e97c42ce4d0c51b8b315d8/enUS.m3u8?v=07fafbd946b222b67aed7148205e47e2&k=bkM1WllVWWJuUGFsQkc0QlA4N3Z2elVEdU5NPV97ImEiOiI5MSwzLGVuVVMsIiwiYyI6MTQzNDc4MjcxNCwiZCI6ImNyYW5pbWUiLCJnIjoiWloiLCJoIjoicnZ6YWk3N3JoOGV5NDAzIiwibCI6NzIwMCwicCI6IjEiLCJyIjoiYzMwZDgyIiwicyI6Mjg3MjcxLCJ0IjoxNDcyMjQyMjAxLCJ2IjozfQ" -W "http://www.crunchyroll.com/swf/StandardVideoPlayer.swf" -o "/media/plasma-blast/Anime/Digimon/Tamers/Digimon Tamers/Digimon Tamers 01x01 [CrunchyRoll].m3u8?v=07fafbd946b222b67aed7148205e47e2&k=bkM1WllVWWJuUGFsQkc0QlA4N3Z2elVEdU5NPV97ImEiOiI5MSwzLGVuVVMsIiwiYyI6MTQzNDc4MjcxNCwiZCI6ImNyYW5pbWUiLCJnIjoiWloiLCJoIjoicnZ6YWk3N3JoOGV5NDAzIiwibCI6NzIwMCwicCI6IjEiLCJyIjoiYzMwZDgyIiwicyI6Mjg3MjcxLCJ0IjoxNDcyMjQyMjAxLCJ2IjozfQ"
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
ERROR: RTMP URL: No :// in url!
WARNING: Couldn't parse the specified url ()!
ERROR: You must specify a hostname (--host) or url (-r "rtmp://host[:port]/playpath") containing a hostname
</blockquote>

<blockquote>    at ChildProcess.exithandler (child_process.js:213:12)</blockquote>

<blockquote>    at emitTwo (events.js:87:13)</blockquote>

<blockquote>    at ChildProcess.emit (events.js:172:7)</blockquote>

<blockquote>    at maybeClose (internal/child_process.js:821:16)</blockquote>

<blockquote>    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)</blockquote>

I don't know if this has any baring on #24 but I'm submitting a bug report.
Kubuntu 16.04 LTS
Node v4.2.6
npm v3.5.2

**Comment by Godzil** [comment]
It is #24
