### ISSUE TITLE
Calling rtmpdump.exe/mkvmerge.exe fails on Windows if system username contains a space

### ISSUE THREAD

**Issue by stordoff** [Deathspike/crunchyroll.js#4]
Example:

E:\CR>crunchyroll -u [user] -p [pass] http://www.crunchyroll.com/fairy-tail
Fetching Fairy Tail 01x01 [CrunchyRoll]
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "'C:\Users\FirstName Surname\AppData\Roaming\npm\node_modules\crunchyroll\bin\rtmpdump.exe' -r [snipped]
The filename, directory name, or volume label syntax is incorrect.

Replacing
    childProcess.exec(command() + ' '
with
    childProcess.exec('"' + command() + '" '
in video/stream.js fixes this. A similar fix works for mkvmerge.exe.

Only tested on Windows 7.

**Comment by Deathspike** [comment]
Good catch! I (obviously) haven't had directories with spaces in them yet, so I never encountered it.

I'll patch this in later tonight. Thank you for the contribution.

**Comment by Deathspike** [comment]
Released in 1.1.2; `npm update -g crunchyroll` to the rescue!
