### ISSUE TITLE
[Feature Request] Drama videos

### ISSUE THREAD

**Issue by stordoff** [Deathspike/crunchyroll.js#5]
Attempting to download dramas currently errors out with "Invalid page." and does not download. The ability to download these shows would be a nice addition.

I've done some poking around, and the (main?) issue seems to be in episode.js. Editing it to reflect the changes shown below enables downloading of drama episodes (at least the ones I tried, albeit with the wrong filenames), so I suspect supporting them may possible. (I haven't used NodeJS before, or JS for a very long, otherwise I'd try to put together a proper patch)

    //WARNING: probably breaks anime downloads and other features
    //var regexp = /Watch\s+(.+?)(?:\s+Season\s+([0-9]+))?\s+Episode\s+([0-9]+)/;
    var regexp = /Episode\s+([0-9]+)/;
    var data = regexp.exec($('title').text());
    //return done(new Error(data));
    if (!swf)
      return done(new Error('Invalid swf.'));
    if (!data)
      return done(new Error('Invalid data.'));
    done(null, {
      id: id,
      episode: parseInt(data[2], 10),
      series: '1',
      swf: swf[1],
      volume: 1

**Comment by Deathspike** [comment]
Released in 1.1.2; `npm update -g crunchyroll` to the rescue!
